### PR TITLE
Explicitly fail if FMBuilder doesn't succeed.

### PR DESCRIPTION
**Pull request by ltratt**
This should fix the issue seen by @vext01 in https://github.com/ykjit/yk/pull/447#issuecomment-987812395.

### CODE REVIEW

**Comment by vext01** [comment]
LGTM:

```
running 3 tests
test lang_tests::echo.py ... ok
test lang_tests::simple.py ... FAILED
test lang_tests::nondeterministic.py ... ok
```

Can a test be added for this?

**Comment by ltratt** [comment]
It's surprisingly awkward to test this sort of thing, because it needs a meta-test. Given that there's a rewrite coming (which will change this stuff anyway), I'm not sure it's worth the effort.

[The rewrite will, if I pull my finger out, test itself better!]

**Comment by vext01** [comment]
OK.

bors r+

**Comment by ltratt** [comment]
Bors seems stuck @vext01 ?

**Comment by vext01** [comment]
bors ping

**Comment by vext01** [comment]
bors may be down...

**Comment by vext01** [comment]
bors ping

**Pull request merged**
