### PR TITLE
Prepare a 0.8.1 release.

### PR DESCRIPTION
**Pull request by ltratt**

### CODE REVIEW

**Comment by ltratt** [comment]
Oops, wait, I've found an issue.

**Comment by ltratt** [comment]
Fixed in https://github.com/softdevteam/lang_tester/pull/124/commits/8f30f238d81f733ce3392a1eacebe53255809e22.

**Comment by vext01** [comment]
Any squashing required?

**Comment by ltratt** [comment]
Squashed.

**Pull request merged**
