### PR TITLE
Start rewriting the poll() loop.

### PR DESCRIPTION
**Pull request by ltratt**
This is shamelessly adapted from extsmaild.

@vext01 Could you try this in-progress PR and let me know what happens in your situation? You might just run into a `todo!()` (a couple of these imply changes elsewhere in lang_tester, but I haven't thought that through yet), but even that will might tell me something.

### CODE REVIEW

**Comment by vext01** [comment]
Wow. Big change! I'll see if i can get a crash.

**Comment by vext01** [comment]
Using this branch I have what appears to be a hangs. Do you want me to investigate?

**Comment by vext01** [comment]
FWIW, the lang tester suite itself hangs too. That will be easier to repro/debug than the jit.

**Comment by ltratt** [comment]
It doesn't hang for me, at least on OpenBSD... Unix, wot fun...

**Comment by vext01** [comment]
I tested on Linux, so could be localised to that?

**Comment by ltratt** [comment]
@vext01 The new commit can run `cargo test && cargo run --example fm_options && cargo run --example rust_lang_tester` on OpenBSD and Linux without hanging. Please see what it does to your yk stuff (there are still `todo`s and so on left, so don't expect miracles)!

**Comment by vext01** [comment]
I'm afraid it still hangs.

**Comment by ltratt** [comment]
@vext01 Please try the new commit. It has survived 1000 runs on Linux and OpenBSD on the test suite, so ... maybe it'll work!

**Comment by ltratt** [comment]
@vext01 It sounds like this is maybe ready for squashing?

**Comment by vext01** [comment]
I think so. I got 1150 iterations of the jit test suite out before hitting an unrelated issue, so I think lang_tester is fixed.

Please squash.

**Comment by ltratt** [comment]
Squashed.

**Comment by vext01** [comment]
Will you be making a new release after this?

**Pull request merged**
