### PR TITLE
lang_tester 0.7.2

### PR DESCRIPTION
**Pull request by ltratt**

### CODE REVIEW

**Comment by vext01** [comment]
Thanks, bors r+

**Comment by ltratt** [comment]
The `bors` command needs to be on a newline, I think.

**Comment by vext01** [comment]
Just noticed this didn't merge. Branch has conflicts apparently...

**Comment by ltratt** [comment]
It did merge -- you can see from the commits at https://github.com/softdevteam/lang_tester/commits/master. I think, somehow, the github PR page didn't notice the merge?

**Comment by vext01** [comment]
wow...

So are we OK to close this then?

**Comment by ltratt** [comment]
I think so.

**Pull request closed without merging**
