### PR TITLE
Enable Bors / BuildBot.

### PR DESCRIPTION
**Pull request by ltratt**

### CODE REVIEW

**Comment by ltratt** [comment]
bors ping

**Comment by ltratt** [comment]
bors try

**Comment by vext01** [comment]
Did you add the repo to the buildbot config on bencher13?

**Comment by ltratt** [comment]
yes

**Comment by vext01** [comment]
Cool.

Did you push dummy trying and staging branches before you restarted buildbot? That may be why buildbot hasn't picked this up.

**Comment by vext01** [comment]
bors try-

**Comment by vext01** [comment]
bors try

**Comment by ltratt** [comment]
bors try

**Comment by ltratt** [comment]
@vext01 If you're OK with this, I need to squash.

**Comment by vext01** [comment]
Please squash.

**Comment by ltratt** [comment]
Squashed.

**Comment by ltratt** [comment]
Why has bors failed but buildbot succeeded I wonder?

**Comment by vext01** [comment]
Crash log says "At least 1 approving review is required by reviewers with write access".

Do we want to turn off "formal" reviews?

**Comment by ltratt** [comment]
Good spot! I've fixed that.

**Pull request merged**
