### PR TITLE
nix currently doesn't build on OpenBSD, so remove it in favour of raw libc.

### PR DESCRIPTION
**Pull request by ltratt**
This also allows us to slightly simplify the code.

### CODE REVIEW

**Comment by ltratt** [comment]
CC @ummarikar

**Comment by ummarikar** [comment]
This looks good to me

**Comment by ltratt** [comment]
You should be able to merge this PR. If not, please shout!

**Comment by ummarikar** [comment]
I've approved the changes but not sure that I have write access

**Comment by ltratt** [comment]
You should have had an email from github inviting you to collaborate on this repo -- it seems you haven't clicked on the link in there yet?

**Comment by ummarikar** [comment]
Of course! Sorry, I seem to be very slow today...

**Pull request merged**
