### PR TITLE
Prepare a 0.5.0 release.

### PR DESCRIPTION
**Pull request by ltratt**

### CODE REVIEW

**Comment by ltratt** [comment]
Hmm, that passes on my machine, and the error on buildbot is surprising:

```
Test executable failed (exit code 1).
```

followed later by:

```
Couldn't set stdin and/or stderr and/or stdout to be non-blocking
```

This *might* be a transitory error.

bors try

**Comment by ltratt** [comment]
@jacob-hughes It looks like it was a transitory error. Can we try merging again?

**Comment by jacob-hughes** [comment]
Sure.

bors r+

**Comment by ltratt** [comment]
Hmph, this one has me stumped at the moment!

bors try

**Comment by jacob-hughes** [comment]
> Build succeeded:

lol

**Comment by jacob-hughes** [comment]
Shall I give it another try

**Comment by ltratt** [comment]
Maybe one more try and if it doesn't work then... I'll have to try something else!

**Pull request merged**
