### PR TITLE
Add support for altering the number of test threads

### PR DESCRIPTION
**Pull request by ltratt**
This is modelled after the same functionality in `cargo test`.

### CODE REVIEW

**Comment by vext01** [comment]
I think I understand why the second commit exists, but this is not the behaviour of existing test suites. How hard is it to always have the option to print the test name regardless of thread count?

**Comment by vext01** [comment]
Otherwise this all looks fine :)

**Comment by ltratt** [comment]
> How hard is it to always have the option to print the test name regardless of thread count?

It is always printed: it's just a question of when.

In a single-threaded context, we print out the name *before* we execute the test file.

In a multi-threaded context, we print out the name *after* we execute the test file (otherwise the test file and "OK"/"Failed" would get separated). AFAICS this is what `cargo test` does too.

**Comment by vext01** [comment]
> In a multi-threaded context, we print out the name after we execute the test file (otherwise the test file and "OK"/"Failed" would get separated).

OK, that's smart. Thanks for clarification.

**Comment by vext01** [comment]
I'm good with this then. Perhaps alter the second commit message to include your clarification on when things are printed?

**Comment by ltratt** [comment]
I can do that at the same time as squashing if you want?

**Comment by vext01** [comment]
Sure. I wasn't sure if you'd squash or not. As you wish :)

**Comment by ltratt** [comment]
Oops, I won't squash... but I will reword!

**Comment by ltratt** [comment]
Reworded.

**Comment by vext01** [comment]
OK

**Pull request merged**
